apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: mpijob
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: All
    ttlSecondsAfterFinished: 60
  sshAuthMountPath: /home/user/.ssh
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: IMAGE
            name: launcher
            command: 
            - mpirun
            args:
            - -n
            - "2"
            - COMMAND
            securityContext:
              runAsUser: 1000
            resources:
              limits:
                cpu: 500m
                memory: 500Mi
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: IMAGE
            name: worker
            securityContext:
              runAsUser: 1000
            resources:
              limits:
                cpu: 2200m
                memory: 64Gi
