plugins:
  - monorepo

site_name: Managed services

nav:
  - Overview: index.md
  - Web Portals:
    - Overview: portals/index.md
    - Galaxy: portals/galaxy/index.md
    - JupyterHub: portals/jupyterhub/index.md
    - BinderHub: portals/binderhub/index.md
    - MagicForceField: portals/magicforcefield/index.md
    - Kubeflow: portals/kubeflow/index.md
  - Task/Workflow execution services:
    - Overview: workflow-execution/index.md
    - TESK/WES: workflow-execution/teswes.md
    - Snakemake: workflow-execution/snakemake.md
    - CWL: workflow-execution/cwl.md
  - VPN: network/secure-vpn/index.md
