site_name: "compute/sensitive-cloud"

nav:
  - Overview: index.md
  - Getting started:
    - getting-started/new-project.md
    - getting-started/connecting-to-sensitive-cloud.md
  - Technical documentation: https://docs.cerit.io
