site_name: "compute/concepts"

edit_uri: edit/master/topics/compute/
nav:
  - Overview: index.md
  - Comparison: comparison.md
  - Use-cases:
    - use-cases/muni-kypo.md
    - use-cases/mmci-muni-bbmri.md
  # - Available Hardware: hw.md
