site_name: "about"
edit_uri: edit/master/topics/about-us/docs
nav:
  - Overview: about-us.md
  - e-INFRA contributor guide:
    - Overview: ./contribute/overview.md
    - Contributing:
      - Set up and work locally: ./contribute/contributing/set-up-and-work-locally.md
      - Work within the GitLab UI: ./contribute/contributing/work-within-gitlab-ui.md
    - Style Guide:
      - Writing practices: ./contribute/style-guide/writing-practices.md
      - Style guide: ./contribute/style-guide/style.md
      - List of checks: ./contribute/style-guide/test-rules.md
    - Technical Details: ./contribute/technical-details.md
